# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [1]:
import itertools as it
words = it.combinations(['A', 'B', 'C'], 2)
for word in words:
  print(word)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [2]:
#your code here
wordSequence = it.cycle(["Python", "is", "fun"])
count = 0
for word in wordSequence:
  if count < 10:
    print(word)
    count += 1
  else:
    break

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [12]:
#your code here
import glob, os
currDir = os.getcwd()
glob.glob(currDir+"/*.py")
# no files are getting printed as there isn't any .py file
# in this dir


[]

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [16]:
html = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

In [22]:
#your code here
from bs4 import BeautifulSoup
soup = BeautifulSoup(html, "html.parser")
print(soup.body.div.p.text)


AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [23]:
#your code here
import re
baseString = "AI is transforming the world. \
With AI we transform the world. AI is awesome"
print(baseString.replace("AI", "Artificial Intelligence"))

Artificial Intelligence is transforming the world. With Artificial Intelligence we transform the world. Artificial Intelligence is awesome


**CP6**: Create a numpy array of 10 zeros.

In [25]:
#your code here
import numpy as np
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [28]:
#your code here
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [31]:
#your code here
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

Since ML models learn from data provided to them, giving them larger amount of data would help them learn more.
More data means more accuracy as the models can derive out more relationships from a larger data which will increase the ***accuracy*** in turn.
In addition, larger datasets can give the model many edge cases to consider from. So the model will be able to generalize in a better manner. The more diverse the data is, the more accurate the model prediction becomes.

Large would be a difficult word to define, but I would say large would be the amount of dataset by which a model can learn different patterns(common and uncommon - edge cases) so that it could generate accurate predictions. But according to my research, the dataset should be in relation with the parameters or the degree of freedom the ML model has. Often times, it's assumed that it should be around 10 times the parameters of the model.


**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

Since most of our daily activities are confined in the digital space, some people have been manipulating computer systems against some users. They would create deepfakes of others as a form of bullying. In addition to this, deepfakes are also being used spread fake news or propaganda, and undermine trust in legitimate media sources.

Another way AI can be used in a bad way is by using it to automate discriminatory or unethical decision-making processes. For example, if an AI model is trained on biased data, it might perpetuate and amplify harmful stereotypes and discriminate against certain groups of people based on their race, gender, or other social identities. This could lead to serious consequences, such as biased hiring decisions, unfair treatment in the criminal justice system, or discriminatory pricing practices. For instance, many facial recognition models trained by european countries are said to lack proper training when it comes to people with another skin color like black.

To mitigate such things,
1. I would recommend governments to expand education to teach citizens what deepfakes are 
2. Use inclusive and unbiased training data. Computer scientists like Dr.Timnit Gebru(who is Ethiopian BTW) are working to reduce the algorithmic bias when it comes to the minority groups.
